### PR TITLE
[WIP] Add README file.

### PR DESCRIPTION
**Pull request by hlokavarapu**
Added a simple straight forward README file. In addition to describing this project and providing credit, this can be expanded to include installation instructions in the future as well as a few example use cases. Just an idea.

### CODE REVIEW

**Review by tjesser-ucdavis-edu — COMMENTED** [review]
A one line README file doesn't really seem worth adding. Is there any other information about the project that can be provided right now?

**Comment by tjesser-ucdavis-edu** [comment]
Sorry, I didn't write a very useful comment, initially. Please see my edit.

**Comment by hlokavarapu** [comment]
Based on similarities for python based libraries such as numpy, scipy, and matplotlib, we could:

- further elaborate on what this project is about
- list supported features that are either complete and/or under active development
- include installation instructions
- include references to documentation or explicitly detail examples of workflow
- developer information
- licensing information

Looking though CIG codes, the only similarity seems to be that a detailed description is included about the project. Other than that, some projects further list and describe the directory structure, other projects include CI tags, links for more information of the library, and/or references to licensing. 

Of these listed, I will work on what is currently possible and what ever is not possible, we may want to consider adding to the README in the near future.

**Comment by hlokavarapu** [comment]
Outdated PR

**Pull request closed without merging**
